version: 2
registries:
  npm-registry-npm-pkg-github-com-deetly-plotly-view:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{secrets.PACKAGE_TOKEN}}"

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    registries: "*"

  - package-ecosystem: npm
    directory: "/apps/data-search"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    registries: "*"

  - package-ecosystem: npm
    directory: "/apps/msearch"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    registries: "*"

  - package-ecosystem: npm
    directory: "/packages/shared/hooks"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    registries: "*"

  - package-ecosystem: npm
    directory: "/packages/shared/metrics"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    registries: "*"

  - package-ecosystem: npm
    directory: "/packages/shared/theme"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    registries: "*"

  - package-ecosystem: npm
    directory: "/packages/shared/ui"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    registries: "*"

  - package-ecosystem: npm
    directory: "/packages/viewers/kafka"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    registries: "*"

  - package-ecosystem: npm
    directory: "/packages/viewers/naisapp"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    registries: "*"

  - package-ecosystem: npm
    directory: "/packages/viewers/naisteam"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    registries: "*"

  - package-ecosystem: npm
    directory: "/packages/viewers/person"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    registries: "*"

  - package-ecosystem: npm
    directory: "/packages/viewers/productarea"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    registries: "*"

  - package-ecosystem: npm
    directory: "/packages/viewers/tabell"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    registries: "*"

  - package-ecosystem: npm
    directory: "/packages/viewers/tableau"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    registries: "*"

  - package-ecosystem: npm
    directory: "/packages/viewers/team"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    registries: "*"

  - package-ecosystem: npm
    directory: "/packages/viewers/begrep"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    registries: "*"

  - package-ecosystem: npm
    directory: "/packages/viewers/office"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    registries: "*"

  - package-ecosystem: npm
    directory: "/packages/viewers/apier"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    registries: "*"

  - package-ecosystem: npm
    directory: "/packages/viewers/bigquery"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    registries: "*"
    
  - package-ecosystem: npm
    directory: "/packages/viewers/parquet"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    registries: "*"
