[[redirects]]
  from = "/datapackage/*"
  to = "http://datapackage-viewer.netlify.com/:splat"
  status = 200
  force = true
  headers = {X-From = "data-search"}

[[redirects]]
  from = "/kafkaprofile/*"
  to = "http://datapackage-viewer.netlify.com/:splat"
  status = 200
  force = true
  headers = {X-From = "data-search"}

[[redirects]]
  from = "/datatable/*"
  to = "http://datapackage-viewer.netlify.com/:splat"
  status = 200
  force = true
  headers = {X-From = "data-search"}

[[redirects]]
  from = "/businessterm/*"
  to = "http://datapackage-viewer.netlify.com/:splat"
  status = 200
  force = true
  headers = {X-From = "data-search"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200