{
  "application_name": "data-catalog-office-viewer",
  "org_name": "navikt",
  "ingress": "https://data.adeo.no/office",
  "ingress_nais_io": "https://data.prod-fss.nais.io/office",
  "kv_path": "secret/dataplattform/datakatalog/prod_fss"
}