apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{application_name}}
  namespace: default
  labels:
    team: dataplattform
spec:
  ingresses:
    - {{ingress}}
    - {{ingress_nais_io}}
  image: {{image}}
  port: 80
  replicas:
      min: 2
      max: 2
      cpuThresholdPercentage: 70
  liveness:
    path: /naisteam/isAlive
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /naisteam/isReady
    timeout: 1
    initialDelay: 5	
    periodSeconds: 5
    failureThreshold: 30
  leaderElection: false
  vault:
    enabled: true
    paths:
      - kvPath: {{kv_path}}
        mountPath: /var/run/secrets/nais.io/common
  prometheus:
    enabled: true
    path: /naisteam
  istio:
    enabled: false
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi