name: 'Deploy'
inputs:
  viewer:
    required: true
  cluster:
    required: true
runs:
  using: "composite"
  steps:
    - run: yarn run setup
      shell: bash
    - run: yarn run shared:build
      shell: bash
      env:
        CI: false
    - run: |
        echo "ENV=$(echo ${{ inputs.cluster }} | cut -d \"-\" -f1)" >> $GITHUB_ENV
        echo "IMAGE=ghcr.io/$GITHUB_REPOSITORY/viewer:${{ inputs.viewer }}-$(date +%Y%m%d)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "PUBLIC_URL=/${{ inputs.viewer }}" >> $GITHUB_ENV
      shell: bash
    - run: yarn $VIEWER:test
      shell: bash
    - run: yarn $VIEWER:build
      shell: bash
      env:
        CI: false
    - run: |
        cd "package/viewers/${{ inputs.viewer }}"
        docker build --tag $IMAGE --build-arg NGINX_VIEWER=${{ inputs.viewer }} -f ../docker/Dockerfile .
      shell: bash
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: docker push $IMAGE
      shell: bash
    - uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: ${{ inputs.cluster }}
        RESOURCE: packages/nais/nais.yaml
        VARS: "packages/viewers/${{ inputs.viewer }}/.nais/${{ ENV }}.yaml"
