name: Build and deploy

on:
  push:
    branches:
      - master

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/data-search:${{ github.sha }}
  PACKAGE_TOKEN: ${{secrets.PACKAGE_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Create app build
        run: npm run build
        env:
          CI: false
      - name: Login to Github package registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
      - name: Build docker image
        run: docker build -t ${IMAGE} .
      - name: Push docker image
        run: docker push ${IMAGE}

  deploy-dev-fss:
    name: Deploy to dev-fss
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-fss
        RESOURCE: naiserator_fss.yaml
        VARS: config-dev-fss.json

  deploy-dev-sbs:
    name: Deploy to dev-sbs
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-sbs
        RESOURCE: naiserator_sbs.yaml
        VARS: config-dev-sbs.json
