name: Build and deploy

on:
  release:
    types: [published]

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/data-search:${{ github.sha }}
  PACKAGE_TOKEN: ${{secrets.PACKAGE_TOKEN}}

jobs:
  deploy-prod-fss:
    name: Deploy to prod-fss
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: prod-fss
        RESOURCE: naiserator_fss.yaml
        VARS: config-prod-fss.json

  deploy-prod-sbs:
    name: Deploy to prod-sbs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: prod-sbs
        RESOURCE: naiserator_sbs.yaml
        VARS: config-prod-sbs.json
