application_name: datapakke-search
team: dataplattform
ingress:
  - https://data.intern.nav.no
  - https://datapakker.intern.nav.no
  - https://datapakker.prod-gcp.nais.io
app_title: Datapakker
postfix: -intern
