version: 1
update_configs:
# root
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
# data-search
  - package_manager: "javascript"
    directory: "/apps/data-search"
    update_schedule: "live"
# shared components
  - package_manager: "javascript"
    directory: "/packages/shared/hooks"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/packages/shared/metrics"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/packages/shared/theme"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/packages/shared/ui"
    update_schedule: "live"
# viewer
  - package_manager: "javascript"
    directory: "/packages/viewer/kafka"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/packages/viewer/naisapp"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/packages/viewer/naisteam"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/packages/viewer/person"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/packages/viewer/productarea"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/packages/viewer/table"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/packages/viewer/tableau"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/packages/viewer/team"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/packages/viewer/term"
    update_schedule: "live"