version: 1
update_configs:
# root
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
# data-search
  - package_manager: "javascript"
    directory: "/apps/data-search"
    update_schedule: "live"
# shared components
  - package_manager: "javascript"
    directory: "/packages/shared/hooks"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/packages/shared/metrics"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/packages/shared/theme"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/packages/shared/ui"
    update_schedule: "live"
# viewer
  - package_manager: "javascript"
    directory: "/packages/viewers/kafka"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/packages/viewers/naisapp"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/packages/viewers/naisteam"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/packages/viewers/office"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/packages/viewers/person"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/packages/viewers/productarea"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/packages/viewers/table"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/packages/viewers/tableau"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/packages/viewers/team"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/packages/viewers/term"
    update_schedule: "live"