apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{application_name}}
  namespace: default
  labels:
    team: dataplattform
spec:
  image: {{ image }}
  port: 80
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 70
  liveness:
    path: /kafka/isAlive
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /kafka/isReady
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  ingresses:
    - {{ingress}}
    - {{ingress_nais_io}}
  leaderElection: false
  vault:
    enabled: true
    paths:
      - kvPath: {{kv_path}}
        mountPath: /var/run/secrets/nais.io/common
  prometheus:
    enabled: true
    path: /kafka
  istio:
    enabled: false
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi