name: Build, test, package and deploy

on: 
  push:
    paths:
      - 'packages/viewers/kafka/**'
    branches:
      - '**'
    tags-ignore:
      - '*.*.*'

env:
  DOCKER_IMAGE: docker.pkg.github.com/${{ github.repository }}/data-catalog-kafka-topic-viewer
  PACKAGE_TOKEN: ${{secrets.PACKAGE_TOKEN}}
  PUBLIC_URL: /kafka

jobs:
  
  test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with: 
        ref: refs/heads/master
    - name: Install dependencies
      run: yarn install
    - name: Run test
      run: yarn test
      env:
        CI: true

  package:
    name: Build and package
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: refs/heads/master
    - name: Install dependencies
      run: yarn install
    - name: Generate tag
      run: |
        # Generate docker image tag
        DATE=$(date +%Y-%m-%d)
        GIT_HASH=$(git rev-parse --short HEAD)
        IMAGE_TAG=${DATE}--${GIT_HASH}
        # write current tag to file
        echo $IMAGE_TAG > docker_img_tag.txt
    - name: Upload img_tag
      uses: actions/upload-artifact@v1
      with:
        name: img_tag
        path: docker_img_tag.txt
    - name: Build
      run: yarn build
      env:
        CI: false
    - name: Build and Publish to Docker Image
      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker build --tag ${DOCKER_IMAGE}:$(cat docker_img_tag.txt) --build-arg PUBLIC_URL=${PUBLIC_URL} .
        docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
        docker push ${DOCKER_IMAGE}:$(cat docker_img_tag.txt)


  deploy:
    name: Build and deploy to dev
    needs: package
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: refs/heads/master
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: img_tag
    - name: Setup image env
      run: |
        VALUE=${DOCKER_IMAGE}:$(cat img_tag/docker_img_tag.txt)
        echo ${VALUE}
        echo ::set-env name=IMAGE::${VALUE}
        echo ${IMAGE}
    - name: Deploy to nais
      uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-fss
        RESOURCE: naiserator.yml
        VARS: config-dev-fss.json
