apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dakan-msearch{{ postfix }}
  namespace: dataplattform
  labels:
    team: dataplattform
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
  liveness:
    path: /isAlive
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  prometheus:
    enabled: true
    path: /
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  env:
    - name: REACT_APP_TITLE
      value: "Åpne data"
    - name: REACT_APP_CONFIG
      value: '{{{ REACT_APP_CONFIG }}}'
  envFrom:
    - configmap: dakan-msearch-config{{ postfix }}
