name: Build test

on: [push]

jobs:

    build:
        runs-on: ubuntu-latest
        needs: install
        steps:
            - uses: actions/checkout@v2
            - run: yarn 
            - run: lerna bootstrap
            - run: yarn person:build