name: Parquet test, package, and deploy

on:
  push:
    paths:
      - .github/workflows/onPushParquet.yml
      - packages/viewers/parquet/**

env:
  VIEWER: parquet
  PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn run setup
    - run: yarn run shared:build
    - run: yarn $VIEWER:test
      env:
        CI: false
    - name: Generate Docker image:tag
      if: github.ref == 'refs/heads/master'
      run: |
        echo "IMAGE=ghcr.io/$GITHUB_REPOSITORY/viewer:$VIEWER-$(date +%Y%m%d)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - if: github.ref == 'refs/heads/master'
      run: yarn $VIEWER:build
      env:
        CI: false
        PUBLIC_URL: "/${{ env.VIEWER }}"
    - if: github.ref == 'refs/heads/master'
      run: |
        cd "packages/viewers/$VIEWER"
        docker build --tag $IMAGE --build-arg NGINX_VIEWER=$VIEWER -f ../../docker/Dockerfile .
    - if: github.ref == 'refs/heads/master'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - if: github.ref == 'refs/heads/master'
      run: docker push $IMAGE
    - if: github.ref == 'refs/heads/master'
      uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-fss
        RESOURCE: packages/nais/nais.yaml
        VARS: packages/viewers/${{ env.VIEWER }}/.nais/dev.yaml
        VAR: VIEWER=${{ env.VIEWER }},IMAGE=${{ env.IMAGE }}
