name: Build test

on: [push]

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: yarn 
            - run: ./node_modules/.bin/lerna bootstrap
            - run: ./node_modules/.bin/lerna link
            - run: ./node_modules/.bin/lerna run build