name: Build test

on: [push]

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with: 
                fetch-depth: "0"
            - run: yarn run setup 
            - run: yarn run shared:build
            - name: tests
              run: yarn run person:test
            - name: build viewer
              run: yarn run person:build