name: Build test

on: [push]

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with: 
                fetch-depth: "0"
            - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
            - run: yarn 
            - run: ./node_modules/.bin/lerna bootstrap
            - run: ./node_modules/.bin/lerna link
            - run: yarn run shared:build
            - run: yarn run person:build