name: Build test

on: [push]

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
            name: install 
            - uses: actions/checkout@v2
            - run: yarn 
            - run: yarn run setup
            - run: yarn person:build