name: Data Search build and deploy

on:
  push:
    paths:
      - 'apps/msearch/**'
    branches:
      - master
    tags-ignore:
      - '*.*.*'

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/dakan-data-search:${{ github.sha }}
  PACKAGE_TOKEN: ${{secrets.PACKAGE_TOKEN}}
  PACKAGE_PATH: apps/msearch

jobs:
  build:
    name: Build, test and package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install dependencies
        run: yarn run setup
      - name: Build shared packages
        run: yarn run shared:build
      - name: Create app build
        run: yarn msearch:build
        env:
          CI: false
      - name: Login to Github package registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
      - name: Build docker image
        run: |
          cd ${PACKAGE_PATH}
          docker build -t ${IMAGE} .
      - name: Push docker image
        run: docker push ${IMAGE}

  deploy-dev-fss:
    name: Deploy to dev-fss
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-fss
        RESOURCE: apps/msearch/naiserator_fss.yaml
        VARS: apps/msearch/config-dev-fss.json

  deploy-dev-sbs:
    name: Deploy to dev-sbs
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-sbs
        RESOURCE: apps/msearch/naiserator_sbs.yaml
        VARS: apps/msearch/config-dev-sbs.json

  deploy-dev-gcp-external:
    name: Deploy to dev-gcp
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-gcp
        RESOURCE: apps/msearch/naiserator_gcp.yaml
        VARS: apps/msearch/config-dev-gcp-external.json