name: Parquet deploy to prod

on:
  push:
    tags:
      - 'msearch-*'

env:
  PACKAGE_TOKEN: ${{secrets.PACKAGE_TOKEN}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: refs/heads/master
    - run: yarn run setup
    - run: yarn run shared:build
    - run: yarn msearch:build
      env:
        CI: false
    - name: Generate Docker image:tag
      run: |
        echo "IMAGE=ghcr.io/$GITHUB_REPOSITORY/msearch:$(date +%Y%m%d)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - run: |
        cd apps/msearch
        docker build --tag $IMAGE .
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: docker push $IMAGE
    - uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: prod-fss
        RESOURCE: apps/msearch/.nais/nais.yaml
        VARS: apps/msearch/.nais/config-prod-intern.yaml
    - uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: prod-gcp
        RESOURCE: apps/msearch/.nais/nais.yaml
        VARS: apps/msearch/.nais/config-prod-ekstern.yaml
