name: Parquet deploy to prod on release

on:
  push:
    tags:
      - 'parquet-*.*.*'

env:
  PACKAGE_TOKEN: ${{secrets.PACKAGE_TOKEN}}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
