name: Bigquery deploy to prod

on:
  push:
    tags:
      - 'bigquery-*'

env:
  VIEWER: bigquery
  PACKAGE_TOKEN: ${{secrets.PACKAGE_TOKEN}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: refs/heads/master
    - run: yarn run setup
    - run: yarn run shared:build
    - run: yarn $VIEWER:build
      env:
        CI: false
        PUBLIC_URL: "/${{ env.VIEWER }}"
    - name: Generate Docker image:tag
      run: |
        echo "IMAGE=ghcr.io/$GITHUB_REPOSITORY/viewer:$VIEWER-$(date +%Y%m%d)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - run: |
        cd "packages/viewers/$VIEWER"
        docker build --tag $IMAGE --build-arg NGINX_VIEWER=$VIEWER -f ../../docker/Dockerfile .
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: docker push $IMAGE
    - uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: prod-fss
        RESOURCE: packages/nais/nais.yaml
        VARS: packages/viewers/${{ env.VIEWER }}/.nais/prod.yaml
        VAR: VIEWER=${{ env.VIEWER }},IMAGE=${{ env.IMAGE }}
