name: Deploy av Parquet
on:
  push:
    paths:
      - .github/workflows/parquet.yaml
      - packages/viewers/parquet/**

env:
  VIEWER: parquet

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy
        with:
          cluster: dev-fss
          viewer: ${{ env.VIEWER }}
