name: Deploy av Parquet
on: push

env:
  VIEWER: parquet

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - if: "!startsWith(github.ref, 'refs/tags/$VIEWER-')"
        uses: ./.github/actions/deploy
        with:
          cluster: dev-fss
          viewer: ${{ $VIEWER }}
      - if: "startsWith(github.ref, 'refs/tags/$VIEWER-')"
        uses: ./.github/actions/deploy
        with:
          cluster: prod-fss
          viewer: ${{ $VIEWER }}
