name: Deploy av Parquet
on:
  push:
    paths:
      - packages/viewers/parquet/**
      - .github/workflows/parquet.yaml

env:
  VIEWER: parquet

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - if: "!startsWith(github.ref, 'refs/tags/$VIEWER-')"
        uses: ./.github/actions/deploy
        with:
          cluster: dev-fss
          viewer: ${{ env.VIEWER }}
      - if: "startsWith(github.ref, 'refs/tags/$VIEWER-')"
        uses: ./.github/actions/deploy
        with:
          cluster: prod-fss
          viewer: ${{ env.VIEWER }}
